# General Settings
CONFIG_PROJECT_NAME="Themis_Server"
CONFIG_VERSION_MAJOR=0
CONFIG_VERSION_MINOR=1
CONFIG_VERSION_SHAME=4
# End of General Settings

# Build Platform
CONFIG_BUILD_LINUX=y
# CONFIG_BUILD_FREERTOS is not set
# CONFIG_BUILD_OSX is not set
# CONFIG_BUILD_WINDOWS is not set
# End of Build Platform

# Build Architecture
CONFIG_ARCH="x86"
# CONFIG_ARCH="ARM"
# End of Build Architecture

# Build Specification
CONFIG_BUILD_DEBUG=1
# CONFIG_BUILD_RELEASE=1
# End of Build Specification

# Themis Configurations
CONFIG_THEMIS_IPV4="127.0.0.1"
CONFIG_THEMIS_PORT=5000
# End of Themis Configurations

# Website URL's
CONFIG_BASE_URL="https://umutunay.github.io/projectthemis-info"
CONFIG_CONTENTS_URL="https://umutunay.github.io/projectthemis-info/contents"
# End of Website URL's
